version: '3'
services:
  envoy:
    network_mode: host
    image: envoyproxy/envoy-dev:b145180d17cac80aa5f9a7801429d52017fea6d1
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
  
  grpc-server:
    image: grpc-server
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
  
  grpc-java-server:
    image: grpc-java-server
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "50051:50051"