// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recommendations.proto

package org.proto;

public final class RecommendationsOuterClass {
  private RecommendationsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.proto.BookCategory}
   */
  public enum BookCategory
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MYSTERY = 0;</code>
     */
    MYSTERY(0),
    /**
     * <code>SCIENCE_FICTION = 1;</code>
     */
    SCIENCE_FICTION(1),
    /**
     * <code>SELF_HELP = 2;</code>
     */
    SELF_HELP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MYSTERY = 0;</code>
     */
    public static final int MYSTERY_VALUE = 0;
    /**
     * <code>SCIENCE_FICTION = 1;</code>
     */
    public static final int SCIENCE_FICTION_VALUE = 1;
    /**
     * <code>SELF_HELP = 2;</code>
     */
    public static final int SELF_HELP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BookCategory valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BookCategory forNumber(int value) {
      switch (value) {
        case 0: return MYSTERY;
        case 1: return SCIENCE_FICTION;
        case 2: return SELF_HELP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BookCategory>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BookCategory> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BookCategory>() {
            public BookCategory findValueByNumber(int number) {
              return BookCategory.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.proto.RecommendationsOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final BookCategory[] VALUES = values();

    public static BookCategory valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BookCategory(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.proto.BookCategory)
  }

  public interface RecommendationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.proto.RecommendationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>.org.proto.BookCategory category = 2;</code>
     * @return The enum numeric value on the wire for category.
     */
    int getCategoryValue();
    /**
     * <code>.org.proto.BookCategory category = 2;</code>
     * @return The category.
     */
    org.proto.RecommendationsOuterClass.BookCategory getCategory();

    /**
     * <code>int32 max_results = 3;</code>
     * @return The maxResults.
     */
    int getMaxResults();
  }
  /**
   * Protobuf type {@code org.proto.RecommendationRequest}
   */
  public static final class RecommendationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.proto.RecommendationRequest)
      RecommendationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecommendationRequest.newBuilder() to construct.
    private RecommendationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecommendationRequest() {
      category_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecommendationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecommendationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              category_ = rawValue;
              break;
            }
            case 24: {

              maxResults_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.proto.RecommendationsOuterClass.RecommendationRequest.class, org.proto.RecommendationsOuterClass.RecommendationRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 2;
    private int category_;
    /**
     * <code>.org.proto.BookCategory category = 2;</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.org.proto.BookCategory category = 2;</code>
     * @return The category.
     */
    @java.lang.Override public org.proto.RecommendationsOuterClass.BookCategory getCategory() {
      @SuppressWarnings("deprecation")
      org.proto.RecommendationsOuterClass.BookCategory result = org.proto.RecommendationsOuterClass.BookCategory.valueOf(category_);
      return result == null ? org.proto.RecommendationsOuterClass.BookCategory.UNRECOGNIZED : result;
    }

    public static final int MAX_RESULTS_FIELD_NUMBER = 3;
    private int maxResults_;
    /**
     * <code>int32 max_results = 3;</code>
     * @return The maxResults.
     */
    @java.lang.Override
    public int getMaxResults() {
      return maxResults_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (category_ != org.proto.RecommendationsOuterClass.BookCategory.MYSTERY.getNumber()) {
        output.writeEnum(2, category_);
      }
      if (maxResults_ != 0) {
        output.writeInt32(3, maxResults_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (category_ != org.proto.RecommendationsOuterClass.BookCategory.MYSTERY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, category_);
      }
      if (maxResults_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxResults_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.proto.RecommendationsOuterClass.RecommendationRequest)) {
        return super.equals(obj);
      }
      org.proto.RecommendationsOuterClass.RecommendationRequest other = (org.proto.RecommendationsOuterClass.RecommendationRequest) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (category_ != other.category_) return false;
      if (getMaxResults()
          != other.getMaxResults()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + category_;
      hash = (37 * hash) + MAX_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getMaxResults();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.proto.RecommendationsOuterClass.RecommendationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.proto.RecommendationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.proto.RecommendationRequest)
        org.proto.RecommendationsOuterClass.RecommendationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.proto.RecommendationsOuterClass.RecommendationRequest.class, org.proto.RecommendationsOuterClass.RecommendationRequest.Builder.class);
      }

      // Construct using org.proto.RecommendationsOuterClass.RecommendationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        category_ = 0;

        maxResults_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationRequest_descriptor;
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.RecommendationRequest getDefaultInstanceForType() {
        return org.proto.RecommendationsOuterClass.RecommendationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.RecommendationRequest build() {
        org.proto.RecommendationsOuterClass.RecommendationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.RecommendationRequest buildPartial() {
        org.proto.RecommendationsOuterClass.RecommendationRequest result = new org.proto.RecommendationsOuterClass.RecommendationRequest(this);
        result.userId_ = userId_;
        result.category_ = category_;
        result.maxResults_ = maxResults_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.proto.RecommendationsOuterClass.RecommendationRequest) {
          return mergeFrom((org.proto.RecommendationsOuterClass.RecommendationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.proto.RecommendationsOuterClass.RecommendationRequest other) {
        if (other == org.proto.RecommendationsOuterClass.RecommendationRequest.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.category_ != 0) {
          setCategoryValue(other.getCategoryValue());
        }
        if (other.getMaxResults() != 0) {
          setMaxResults(other.getMaxResults());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.proto.RecommendationsOuterClass.RecommendationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.proto.RecommendationsOuterClass.RecommendationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int category_ = 0;
      /**
       * <code>.org.proto.BookCategory category = 2;</code>
       * @return The enum numeric value on the wire for category.
       */
      @java.lang.Override public int getCategoryValue() {
        return category_;
      }
      /**
       * <code>.org.proto.BookCategory category = 2;</code>
       * @param value The enum numeric value on the wire for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryValue(int value) {
        
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.proto.BookCategory category = 2;</code>
       * @return The category.
       */
      @java.lang.Override
      public org.proto.RecommendationsOuterClass.BookCategory getCategory() {
        @SuppressWarnings("deprecation")
        org.proto.RecommendationsOuterClass.BookCategory result = org.proto.RecommendationsOuterClass.BookCategory.valueOf(category_);
        return result == null ? org.proto.RecommendationsOuterClass.BookCategory.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.proto.BookCategory category = 2;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(org.proto.RecommendationsOuterClass.BookCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        category_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.proto.BookCategory category = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = 0;
        onChanged();
        return this;
      }

      private int maxResults_ ;
      /**
       * <code>int32 max_results = 3;</code>
       * @return The maxResults.
       */
      @java.lang.Override
      public int getMaxResults() {
        return maxResults_;
      }
      /**
       * <code>int32 max_results = 3;</code>
       * @param value The maxResults to set.
       * @return This builder for chaining.
       */
      public Builder setMaxResults(int value) {
        
        maxResults_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 max_results = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxResults() {
        
        maxResults_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.proto.RecommendationRequest)
    }

    // @@protoc_insertion_point(class_scope:org.proto.RecommendationRequest)
    private static final org.proto.RecommendationsOuterClass.RecommendationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.proto.RecommendationsOuterClass.RecommendationRequest();
    }

    public static org.proto.RecommendationsOuterClass.RecommendationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendationRequest>
        PARSER = new com.google.protobuf.AbstractParser<RecommendationRequest>() {
      @java.lang.Override
      public RecommendationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecommendationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecommendationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecommendationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.proto.RecommendationsOuterClass.RecommendationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BookRecommendationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.proto.BookRecommendation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();
  }
  /**
   * Protobuf type {@code org.proto.BookRecommendation}
   */
  public static final class BookRecommendation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.proto.BookRecommendation)
      BookRecommendationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookRecommendation.newBuilder() to construct.
    private BookRecommendation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookRecommendation() {
      title_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BookRecommendation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookRecommendation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.proto.RecommendationsOuterClass.internal_static_org_proto_BookRecommendation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.proto.RecommendationsOuterClass.internal_static_org_proto_BookRecommendation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.proto.RecommendationsOuterClass.BookRecommendation.class, org.proto.RecommendationsOuterClass.BookRecommendation.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.proto.RecommendationsOuterClass.BookRecommendation)) {
        return super.equals(obj);
      }
      org.proto.RecommendationsOuterClass.BookRecommendation other = (org.proto.RecommendationsOuterClass.BookRecommendation) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.BookRecommendation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.proto.RecommendationsOuterClass.BookRecommendation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.proto.BookRecommendation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.proto.BookRecommendation)
        org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_BookRecommendation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_BookRecommendation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.proto.RecommendationsOuterClass.BookRecommendation.class, org.proto.RecommendationsOuterClass.BookRecommendation.Builder.class);
      }

      // Construct using org.proto.RecommendationsOuterClass.BookRecommendation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_BookRecommendation_descriptor;
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.BookRecommendation getDefaultInstanceForType() {
        return org.proto.RecommendationsOuterClass.BookRecommendation.getDefaultInstance();
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.BookRecommendation build() {
        org.proto.RecommendationsOuterClass.BookRecommendation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.BookRecommendation buildPartial() {
        org.proto.RecommendationsOuterClass.BookRecommendation result = new org.proto.RecommendationsOuterClass.BookRecommendation(this);
        result.id_ = id_;
        result.title_ = title_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.proto.RecommendationsOuterClass.BookRecommendation) {
          return mergeFrom((org.proto.RecommendationsOuterClass.BookRecommendation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.proto.RecommendationsOuterClass.BookRecommendation other) {
        if (other == org.proto.RecommendationsOuterClass.BookRecommendation.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.proto.RecommendationsOuterClass.BookRecommendation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.proto.RecommendationsOuterClass.BookRecommendation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.proto.BookRecommendation)
    }

    // @@protoc_insertion_point(class_scope:org.proto.BookRecommendation)
    private static final org.proto.RecommendationsOuterClass.BookRecommendation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.proto.RecommendationsOuterClass.BookRecommendation();
    }

    public static org.proto.RecommendationsOuterClass.BookRecommendation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookRecommendation>
        PARSER = new com.google.protobuf.AbstractParser<BookRecommendation>() {
      @java.lang.Override
      public BookRecommendation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookRecommendation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookRecommendation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookRecommendation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.proto.RecommendationsOuterClass.BookRecommendation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecommendationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.proto.RecommendationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    java.util.List<org.proto.RecommendationsOuterClass.BookRecommendation> 
        getRecommendationsList();
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    org.proto.RecommendationsOuterClass.BookRecommendation getRecommendations(int index);
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    int getRecommendationsCount();
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    java.util.List<? extends org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder> 
        getRecommendationsOrBuilderList();
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder getRecommendationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.proto.RecommendationResponse}
   */
  public static final class RecommendationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.proto.RecommendationResponse)
      RecommendationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecommendationResponse.newBuilder() to construct.
    private RecommendationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecommendationResponse() {
      recommendations_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecommendationResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecommendationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                recommendations_ = new java.util.ArrayList<org.proto.RecommendationsOuterClass.BookRecommendation>();
                mutable_bitField0_ |= 0x00000001;
              }
              recommendations_.add(
                  input.readMessage(org.proto.RecommendationsOuterClass.BookRecommendation.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.proto.RecommendationsOuterClass.RecommendationResponse.class, org.proto.RecommendationsOuterClass.RecommendationResponse.Builder.class);
    }

    public static final int RECOMMENDATIONS_FIELD_NUMBER = 1;
    private java.util.List<org.proto.RecommendationsOuterClass.BookRecommendation> recommendations_;
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.proto.RecommendationsOuterClass.BookRecommendation> getRecommendationsList() {
      return recommendations_;
    }
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder> 
        getRecommendationsOrBuilderList() {
      return recommendations_;
    }
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    @java.lang.Override
    public int getRecommendationsCount() {
      return recommendations_.size();
    }
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    @java.lang.Override
    public org.proto.RecommendationsOuterClass.BookRecommendation getRecommendations(int index) {
      return recommendations_.get(index);
    }
    /**
     * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
     */
    @java.lang.Override
    public org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder getRecommendationsOrBuilder(
        int index) {
      return recommendations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < recommendations_.size(); i++) {
        output.writeMessage(1, recommendations_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < recommendations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, recommendations_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.proto.RecommendationsOuterClass.RecommendationResponse)) {
        return super.equals(obj);
      }
      org.proto.RecommendationsOuterClass.RecommendationResponse other = (org.proto.RecommendationsOuterClass.RecommendationResponse) obj;

      if (!getRecommendationsList()
          .equals(other.getRecommendationsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRecommendationsCount() > 0) {
        hash = (37 * hash) + RECOMMENDATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getRecommendationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.proto.RecommendationsOuterClass.RecommendationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.proto.RecommendationsOuterClass.RecommendationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.proto.RecommendationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.proto.RecommendationResponse)
        org.proto.RecommendationsOuterClass.RecommendationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.proto.RecommendationsOuterClass.RecommendationResponse.class, org.proto.RecommendationsOuterClass.RecommendationResponse.Builder.class);
      }

      // Construct using org.proto.RecommendationsOuterClass.RecommendationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRecommendationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (recommendationsBuilder_ == null) {
          recommendations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          recommendationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.proto.RecommendationsOuterClass.internal_static_org_proto_RecommendationResponse_descriptor;
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.RecommendationResponse getDefaultInstanceForType() {
        return org.proto.RecommendationsOuterClass.RecommendationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.RecommendationResponse build() {
        org.proto.RecommendationsOuterClass.RecommendationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.proto.RecommendationsOuterClass.RecommendationResponse buildPartial() {
        org.proto.RecommendationsOuterClass.RecommendationResponse result = new org.proto.RecommendationsOuterClass.RecommendationResponse(this);
        int from_bitField0_ = bitField0_;
        if (recommendationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            recommendations_ = java.util.Collections.unmodifiableList(recommendations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.recommendations_ = recommendations_;
        } else {
          result.recommendations_ = recommendationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.proto.RecommendationsOuterClass.RecommendationResponse) {
          return mergeFrom((org.proto.RecommendationsOuterClass.RecommendationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.proto.RecommendationsOuterClass.RecommendationResponse other) {
        if (other == org.proto.RecommendationsOuterClass.RecommendationResponse.getDefaultInstance()) return this;
        if (recommendationsBuilder_ == null) {
          if (!other.recommendations_.isEmpty()) {
            if (recommendations_.isEmpty()) {
              recommendations_ = other.recommendations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRecommendationsIsMutable();
              recommendations_.addAll(other.recommendations_);
            }
            onChanged();
          }
        } else {
          if (!other.recommendations_.isEmpty()) {
            if (recommendationsBuilder_.isEmpty()) {
              recommendationsBuilder_.dispose();
              recommendationsBuilder_ = null;
              recommendations_ = other.recommendations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              recommendationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecommendationsFieldBuilder() : null;
            } else {
              recommendationsBuilder_.addAllMessages(other.recommendations_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.proto.RecommendationsOuterClass.RecommendationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.proto.RecommendationsOuterClass.RecommendationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.proto.RecommendationsOuterClass.BookRecommendation> recommendations_ =
        java.util.Collections.emptyList();
      private void ensureRecommendationsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          recommendations_ = new java.util.ArrayList<org.proto.RecommendationsOuterClass.BookRecommendation>(recommendations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.proto.RecommendationsOuterClass.BookRecommendation, org.proto.RecommendationsOuterClass.BookRecommendation.Builder, org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder> recommendationsBuilder_;

      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public java.util.List<org.proto.RecommendationsOuterClass.BookRecommendation> getRecommendationsList() {
        if (recommendationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recommendations_);
        } else {
          return recommendationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public int getRecommendationsCount() {
        if (recommendationsBuilder_ == null) {
          return recommendations_.size();
        } else {
          return recommendationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public org.proto.RecommendationsOuterClass.BookRecommendation getRecommendations(int index) {
        if (recommendationsBuilder_ == null) {
          return recommendations_.get(index);
        } else {
          return recommendationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder setRecommendations(
          int index, org.proto.RecommendationsOuterClass.BookRecommendation value) {
        if (recommendationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecommendationsIsMutable();
          recommendations_.set(index, value);
          onChanged();
        } else {
          recommendationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder setRecommendations(
          int index, org.proto.RecommendationsOuterClass.BookRecommendation.Builder builderForValue) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.set(index, builderForValue.build());
          onChanged();
        } else {
          recommendationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder addRecommendations(org.proto.RecommendationsOuterClass.BookRecommendation value) {
        if (recommendationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecommendationsIsMutable();
          recommendations_.add(value);
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder addRecommendations(
          int index, org.proto.RecommendationsOuterClass.BookRecommendation value) {
        if (recommendationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecommendationsIsMutable();
          recommendations_.add(index, value);
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder addRecommendations(
          org.proto.RecommendationsOuterClass.BookRecommendation.Builder builderForValue) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.add(builderForValue.build());
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder addRecommendations(
          int index, org.proto.RecommendationsOuterClass.BookRecommendation.Builder builderForValue) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.add(index, builderForValue.build());
          onChanged();
        } else {
          recommendationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder addAllRecommendations(
          java.lang.Iterable<? extends org.proto.RecommendationsOuterClass.BookRecommendation> values) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recommendations_);
          onChanged();
        } else {
          recommendationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder clearRecommendations() {
        if (recommendationsBuilder_ == null) {
          recommendations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          recommendationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public Builder removeRecommendations(int index) {
        if (recommendationsBuilder_ == null) {
          ensureRecommendationsIsMutable();
          recommendations_.remove(index);
          onChanged();
        } else {
          recommendationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public org.proto.RecommendationsOuterClass.BookRecommendation.Builder getRecommendationsBuilder(
          int index) {
        return getRecommendationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder getRecommendationsOrBuilder(
          int index) {
        if (recommendationsBuilder_ == null) {
          return recommendations_.get(index);  } else {
          return recommendationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public java.util.List<? extends org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder> 
           getRecommendationsOrBuilderList() {
        if (recommendationsBuilder_ != null) {
          return recommendationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recommendations_);
        }
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public org.proto.RecommendationsOuterClass.BookRecommendation.Builder addRecommendationsBuilder() {
        return getRecommendationsFieldBuilder().addBuilder(
            org.proto.RecommendationsOuterClass.BookRecommendation.getDefaultInstance());
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public org.proto.RecommendationsOuterClass.BookRecommendation.Builder addRecommendationsBuilder(
          int index) {
        return getRecommendationsFieldBuilder().addBuilder(
            index, org.proto.RecommendationsOuterClass.BookRecommendation.getDefaultInstance());
      }
      /**
       * <code>repeated .org.proto.BookRecommendation recommendations = 1;</code>
       */
      public java.util.List<org.proto.RecommendationsOuterClass.BookRecommendation.Builder> 
           getRecommendationsBuilderList() {
        return getRecommendationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.proto.RecommendationsOuterClass.BookRecommendation, org.proto.RecommendationsOuterClass.BookRecommendation.Builder, org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder> 
          getRecommendationsFieldBuilder() {
        if (recommendationsBuilder_ == null) {
          recommendationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.proto.RecommendationsOuterClass.BookRecommendation, org.proto.RecommendationsOuterClass.BookRecommendation.Builder, org.proto.RecommendationsOuterClass.BookRecommendationOrBuilder>(
                  recommendations_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          recommendations_ = null;
        }
        return recommendationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.proto.RecommendationResponse)
    }

    // @@protoc_insertion_point(class_scope:org.proto.RecommendationResponse)
    private static final org.proto.RecommendationsOuterClass.RecommendationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.proto.RecommendationsOuterClass.RecommendationResponse();
    }

    public static org.proto.RecommendationsOuterClass.RecommendationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecommendationResponse>
        PARSER = new com.google.protobuf.AbstractParser<RecommendationResponse>() {
      @java.lang.Override
      public RecommendationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecommendationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecommendationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecommendationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.proto.RecommendationsOuterClass.RecommendationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_proto_RecommendationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_proto_RecommendationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_proto_BookRecommendation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_proto_BookRecommendation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_proto_RecommendationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_proto_RecommendationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025recommendations.proto\022\torg.proto\"h\n\025Re" +
      "commendationRequest\022\017\n\007user_id\030\001 \001(\005\022)\n\010" +
      "category\030\002 \001(\0162\027.org.proto.BookCategory\022" +
      "\023\n\013max_results\030\003 \001(\005\"/\n\022BookRecommendati" +
      "on\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\"P\n\026Recomme" +
      "ndationResponse\0226\n\017recommendations\030\001 \003(\013" +
      "2\035.org.proto.BookRecommendation*?\n\014BookC" +
      "ategory\022\013\n\007MYSTERY\020\000\022\023\n\017SCIENCE_FICTION\020" +
      "\001\022\r\n\tSELF_HELP\020\0022c\n\017Recommendations\022P\n\tR" +
      "ecommend\022 .org.proto.RecommendationReque" +
      "st\032!.org.proto.RecommendationResponseb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_proto_RecommendationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_proto_RecommendationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_proto_RecommendationRequest_descriptor,
        new java.lang.String[] { "UserId", "Category", "MaxResults", });
    internal_static_org_proto_BookRecommendation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_proto_BookRecommendation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_proto_BookRecommendation_descriptor,
        new java.lang.String[] { "Id", "Title", });
    internal_static_org_proto_RecommendationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_proto_RecommendationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_proto_RecommendationResponse_descriptor,
        new java.lang.String[] { "Recommendations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
