/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.0
// 	protoc              v3.18.0
// source: recommendations.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as recommendations_pb from './recommendations_pb';


export class RecommendationsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRecommend = new grpcWeb.MethodDescriptor(
    '/Recommendations/Recommend',
    grpcWeb.MethodType.UNARY,
    recommendations_pb.RecommendationRequest,
    recommendations_pb.RecommendationResponse,
    (request: recommendations_pb.RecommendationRequest) => {
      return request.serializeBinary();
    },
    recommendations_pb.RecommendationResponse.deserializeBinary
  );

  recommend(
    request: recommendations_pb.RecommendationRequest,
    metadata: grpcWeb.Metadata | null): Promise<recommendations_pb.RecommendationResponse>;

  recommend(
    request: recommendations_pb.RecommendationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: recommendations_pb.RecommendationResponse) => void): grpcWeb.ClientReadableStream<recommendations_pb.RecommendationResponse>;

  recommend(
    request: recommendations_pb.RecommendationRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: recommendations_pb.RecommendationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Recommendations/Recommend',
        request,
        metadata || {},
        this.methodDescriptorRecommend,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Recommendations/Recommend',
    request,
    metadata || {},
    this.methodDescriptorRecommend);
  }

}

